TickApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/todolist/', include('todolist.urls', namespace='todolist')),
    path('api/todolist/v2/', include('todolist.v2.urls', namespace='todolist-v2')),
    path('api/todolist/v3/', include('todolist.v3.urls', namespace='todolist-v3')),
    path('api/shorturl/', include('url_shortener.urls', namespace='url_shortener')),
    path('tickapp/', include('frontend.urls', namespace='frontend')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name='index'),
    path('todolists/', views.todolist_list, name='todolist_list'),
    path('todolists/create/', views.todolist_create, name='todolist_create'),
    path('todolists/created-successfully/', views.created_successfully, name='successful'),
    path('todolists/<int:list_id>/', views.todolist_detail, name='todolist_detail'),
    path('todolists/<int:list_id>/edit', views.todolist_edit, name='todolist_edit'),
    path('todolists/<int:list_id>/import', views.task_import, name='task_import'),
    path('tasks/', views.task_list, name='task_list'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/edit', views.task_edit, name='task_edit'),
    path('tasks/<int:task_id>/export', views.task_export, name='task_export'),
    path('shorten/', views.url_shortener, name='url_shortener'),
]

url_shortener/urls.py
from django.urls import path
from . import views

app_name = 'url_shortener'

urlpatterns = [
    path('', views.Shorten.as_view(), name='Shorten')
]

url_shortener/models.py
from django.db import models


class UrlDict(models.Model):
    key = models.CharField(max_length=200)
    original_url = models.CharField(max_length=500)

    def __str__(self):
        return self.key

url_shortener/models/UrlDict.py
from django.db import models


class UrlDict(models.Model):
    key = models.CharField(max_length=200)
    original_url = models.CharField(max_length=500)

    def __str__(self):
        return self.key

url_shortener/models/url_dict.py
from django.db import models


class UrlDict(models.Model):
    key = models.CharField(max_length=200)
    original_url = models.CharField(max_length=500)

    def __str__(self):
        return self.key

frontend/forms/task_form.py
from django import forms

from todolist.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'deadline', 'importance', 'file', 'image', "done"]

frontend/forms/task_import_form.py
from django import forms

from todolist.models import Task


class TaskImportForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['url']

frontend/forms/todolist_form.py
from django import forms

from todolist.models import TodoList


class TodolistForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name', 'description', 'tasks']

frontend/views/created_successfully.py
from django.shortcuts import render


def created_successfully(request):
    if request.method == 'GET':
        return render(request, 'frontend/create_successful.html')

    return render(request, 'frontend/wrong_method.html')

frontend/views/index.py
from django.shortcuts import render


def index(request):
    if request.method == "GET":
        return render(request, 'frontend/index.html')

    return render(request, 'frontend/wrong_method.html')

frontend/views/index_view.py
from django.shortcuts import render
from django.views.generic import View

from todolist.models import CustomUser


class IndexView(View):
    def get(self, request):
        user: CustomUser = request.user
        lists = user.todolist_set.all()
        context = {
            'lists': lists,
            'user': request.user.username
        }
        return render(request, 'frontend/todolist_list.html', context)

frontend/views/list_create.py
from django.shortcuts import render

from frontend.forms import TodolistForm


def list_create(request):
    if request.method == 'GET':
        form = TodolistForm
        return render(request, "frontend/list_form_create.html", {"form": form})

    return render(request, 'frontend/wrong_method.html')

frontend/views/list_detail.py
from django.shortcuts import render, get_object_or_404

from todolist.models import CustomUser, TodoList


def list_detail(request, list_id):
    if request.method == 'GET':
        current_list = get_object_or_404(TodoList, id=list_id)
        user: CustomUser = request.user
        if user.todolist_set.contains(current_list):
            return render(request, 'frontend/todolist_detail.html', {'list': current_list})
        else:
            return render(request, 'frontend/access_denied.html')

    return render(request, 'frontend/wrong_method.html')

frontend/views/list_edit.py
from django.shortcuts import render, get_object_or_404

from todolist.models import TodoList
from frontend.forms import TodolistForm


def list_edit(request, list_id):
    if request.method == 'GET':
        prev_list = get_object_or_404(TodoList, id=list_id)
        form = TodolistForm(
            {'name': prev_list.name, 'description': prev_list.description, 'tasks': prev_list.tasks.all()})
        return render(request, 'frontend/list_form_edit.html', {"form": form, "list_id": list_id})

    return render(request, 'frontend/wrong_method.html')

frontend/views/task_create.py
from django.shortcuts import render

from frontend.forms import TaskForm


def task_create(request):
    if request.method == 'GET':
        form = TaskForm()
        return render(request, "frontend/task_form_create.html", {"form": form})

    return render(request, 'frontend/wrong_method.html')

frontend/views/task_detail.py
from django.shortcuts import render, get_object_or_404

from todolist.models import Task


def task_detail(request, task_id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=task_id)
        return render(request, 'frontend/task_detail.html', {'task': task})

    return render(request, 'frontend/wrong_method.html')

frontend/views/task_edit.py
from django.shortcuts import render, get_object_or_404

from todolist.models import Task
from frontend.forms import TaskForm


def task_edit(request, task_id):
    if request.method == 'GET':
        prev_task = get_object_or_404(Task, id=task_id)
        form = TaskForm({'name': prev_task.name, 'deadline': prev_task.deadline, 'importance': prev_task.importance,
                         'file': prev_task.file, 'image': prev_task.image, 'done': prev_task.done})
        return render(request, 'frontend/task_form_edit.html', {"form": form, "task_id": task_id})

    return render(request, 'frontend/wrong_method.html')

frontend/views/task_export.py
from django.shortcuts import render, get_object_or_404

from todolist.models import Task


def task_export(request, task_id=None):
    if request.method == 'GET':
        task = get_object_or_404(Task, id=task_id)
        return render(request, 'frontend/task_export.html', {'task': task})

    return render(request, 'frontend/wrong_method.html')

frontend/views/task_import.py
from django.shortcuts import render

from frontend.forms import TaskImportForm


def task_import(request, list_id):
    if request.method == 'GET':
        form = TaskImportForm()
        return render(request, 'frontend/task_import.html', {'list_id': list_id, 'form': form})

    return render(request, 'frontend/wrong_method.html')

frontend/views/task_list.py
from django.shortcuts import render


def task_list(request):
    if request.method == 'GET':
        return render(request, 'frontend/task_list.html')

    return render(request, 'frontend/wrong_method.html')

frontend/views/todolist_create.py
from django.shortcuts import render

from frontend.forms import TodolistForm


def todolist_create(request):
    if request.method == 'GET':
        form = TodolistForm
        return render(request, "frontend/todolist_form_create.html", {"form": form})

    return render(request, 'frontend/wrong_method.html')

frontend/views/todolist_detail.py
from django.shortcuts import render, get_object_or_404

from todolist.models import CustomUser, TodoList


def todolist_detail(request, list_id):
    if request.method == 'GET':
        current_list = get_object_or_404(TodoList, id=list_id)
        user: CustomUser = request.user
        if user.todolist_set.contains(current_list):
            return render(request, 'frontend/todolist_detail.html', {'list': current_list})
        else:
            return render(request, 'frontend/access_denied.html')

    return render(request, 'frontend/wrong_method.html')

frontend/templates/frontend/create_successful.html
<h3>Created the task successfully</h3>
<a href="{% url 'frontend:index' %}">Return to dashboard</a>

frontend/templates/frontend/error_login.html
<h3>You need to log in first!</h3>
<p > Log in <a href="http://127.0.0.1:8000/admin/">here</a> </p>

frontend/templates/frontend/index.html
{% extends 'base.html' %}
{% block main %}
    <h2>Welcome to TickApp</h2>
    <a href="{% url 'frontend:todolist_list' %}">Go to your todo lists</a><br>
    <a href="{% url 'frontend:task_list' %}">Go to your tasks</a>
{% endblock %}

frontend/templates/frontend/list_form_create.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    
    {{ form }}
    <button id="submit">Submit</button>

    <script src="{% static 'frontend/js/todolist.list.js' %}"></script>

{% endblock %}

frontend/templates/frontend/list_form_edit.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    
    <div id="todolist" data-id="{{ list_id }}"></div>
    
    {{ form }}
    <button id="save">Save</button>
    

    <script src="{% static 'frontend/js/todolist.detail.js' %}"></script>

{% endblock %}

frontend/templates/frontend/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1>{{ task }}</h1>
     <ul>   
         {%  if task.done %}
             <li><p>This task is already done</p></li>
         {% else %}    
             <li><p>This task is yet to be done</p></li>
         {% endif %}
         <button id="detail-btn">Show more details</button>
         <div id="details">
             
         </div>
     </ul>
    
    <button id="delete-btn">Delete</button>
    <p id="delete-response"></p>
    
    <a href="{% url 'frontend:task_edit' task.id %}"> Edit the task</a><br>
    <a href="{% url 'frontend:task_export' task.id %}"> Share the Task!</a><br>
    <a href="{% url 'frontend:index' %}"> Return to the dashboard</a>
    
    <div id="task" data-id="{{ task.id }}" data-date-added="{{ task.date_added }}" data-deadline="{{ task.deadline }}" 
         data-importance="{{ task.importance }}" data-file="{{ task.file }}" data-image="{{ task.image }}"></div>
    
    <script>
        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) return parts.pop().split(';').shift();
        }
    
        $(document).ready( function () {
            $("#detail-btn").click( function (){
                $.ajax({
                    method: "GET",
                    url: `http://127.0.0.1:8000/api/todolist/v3/tasks/{{ task.id }}/`,
                    success: function () {
                        $("#details").append("<li><p>Added at: {{ task.date_added}}</p></li>\n" +
                            "             <li><p>Deadline is at: {{ task.deadline}}</p></li>\n" +
                            "             <li><p>Importance: {{ task.importance}}</p></li>\n" +
                            "             {% if task.file %}\n" +
                            "                <li> <a href=\"{{ task.file.url }}\"> {{ task.file }}</a> </li>\n" +
                            "             {% endif %}\n" +
                            "             {% if task.image %}\n" +
                            "                <li> <img alt=\"\" src={{ task.image.url }}> </li>\n" +
                            "             {% endif %}");
                        $("#detail-btn").remove();
                    },
                    cache: false,
                });
            });
            
            $("#delete-btn").click( function (){
                $.ajax({
                    method: "DELETE",
                    url: `http://127.0.0.1:8000/api/todolist/v3/tasks/{{ task.id }}/`,
                    headers: {
                        'X-CSRFToken': getCookie('csrftoken')
                    },
                    success: function(response){
                        $("#delete-response").text("Deleted successfully")
                        setTimeout(function (){
                            window.location.replace("http://127.0.0.1:8000/todolists/");
                        }, 1000)
                    },
                    cache: false,
                })
            })
        });
    </script>
        

{% endblock %}

frontend/templates/frontend/task_export.html
{% extends 'base.html' %}
{% block main %}

    <h3>The link for sharing the task "{{ task }}" is below</h3>
    <button id="link-btn">Get link</button>
    <div id="link">
    </div>
    <a href="{% url 'frontend:index' %}">Return to dashboard</a>

    <script>
        $("#link-btn").click( function (){
            $.ajax({
               method: "GET",
               url: "http://127.0.0.1:8000/api/todolist/v3/tasks/{{ task.id }}/export/" ,
               success: function (response) {
                   $("#link").text(response);
               },
               cache: false
            });
            $("#link-btn").remove();
        });
    </script>

{% endblock %}

frontend/templates/frontend/task_form_create.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    
    <form id="data" method="post" enctype="multipart/form-data">
        {{ form }}
        <input type="submit" value="Submit" id="submit">
    </form>
    
    <script>
        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) return parts.pop().split(';').shift();
        }
        
        $("form#data").submit(function(e) {
            e.preventDefault();    
            let formData = new FormData(this);
        
            $.ajax({
                url: `http://127.0.0.1:8000/api/todolist/v3/tasks/`,
                type: 'POST',
                data: formData,
                headers: {
                            'X-CSRFToken': getCookie('csrftoken')
                },
                success: function () {
                    setTimeout(() => {
                            window.location.replace('http://127.0.0.1:8000/tickapp/todolists/');
                        }, 1000);
                },
                cache: false,
                contentType: false,
                processData: false
            });
        });
    </script>
{% endblock %}

frontend/templates/frontend/task_form_edit.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    
    <form id="data" method="post" enctype="multipart/form-data">
        {{ form }}
        <input type="submit" value="Save" id="save">
    </form>
    
    <script>
        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) return parts.pop().split(';').shift();
        }
        
        $("form#data").submit(function(e) {
            e.preventDefault();    
            let formData = new FormData(this);
        
            $.ajax({
                url: `http://127.0.0.1:8000/api/todolist/v3/tasks/{{ task_id }}/`,
                type: 'PUT',
                data: formData,
                headers: {
                            'X-CSRFToken': getCookie('csrftoken')
                },
                success: function () {
                    setTimeout(() => {
                            window.location.replace('http://127.0.0.1:8000/tickapp/');
                        }, 1000);
                },
                cache: false,
                contentType: false,
                processData: false
            });
        });
    </script>
{% endblock %}

frontend/templates/frontend/task_import.html
{% extends 'base.html' %}
{% block main %}

    <form method="post" id="data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    
    <p id="response"></p>
    
    <script>
        $("form#data").submit( function(e) {
            e.preventDefault();
            let formData = new FormData(this);
            console.log(formData)
            $.ajax({
                method: "POST",
                url: "http://127.0.0.1:8000/api/todolist/v3/todo-lists/{{ list_id }}/import_task/",
                data: formData,
                success: function (response){
                    $("#response").text(response);
                    setTimeout(function (){
                        window.location.replace("http://127.0.0.1:8000/tickapp/{{ list_id }}/");
                    }, 1000)
                },
                error: function (response){
                    alert(response);
                },
                cache: false,
                contentType: false,
                processData: false
            });
        });
    </script>

{% endblock %}

frontend/templates/frontend/task_list.html
{% extends 'base.html' %}
{% block main %}
    <h2>{{ user }}'s tasks</h2>
    <ul id="tasks">
    
    </ul>

    <button id="btn" >Get tasks</button><br>
    
    <a href="{% url 'frontend:task_create' %}">Create a new list</a><br>

    <script>
        $("#btn").click( function (){
            $.ajax({
                method: "GET",
                url: "http://127.0.0.1:8000/api/todolist/v3/tasks/",
                success: function (response){
                    $.each(response.results, function (i, task){
                        $("#tasks").append("<li><a href=\"" + task.id + "\">" + task.name + "</a></li>");
                    });
                },
                cache: false,
            })
            $("#btn").remove();
        });
    </script>
{% endblock %}

frontend/templates/frontend/todolist_detail.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1>{{ list }}</h1>
    <h3>Tasks: </h3>
    <ul>
        {% for task in list.tasks.all %}
            <li><a href="{% url 'frontend:task_detail' task.id %}">{{ task.name }}</a></li>
        {% endfor %}
    </ul>

    <div id="todolist" data-id="{{ list.id }}" data-description="{{ list.description }}" data-pubdate="{{ list.pub_date }}"></div>

    <div id="details">

    </div>

    <button id="detail-btn">More Details</button><br>

    <button id="delete-btn">Delete</button><br>
    <a id="delete-response"></a><br>
    
    <a href="{% url 'frontend:todolist_edit' list.id %}">Edit this list</a><br>
    <a href="{% url 'frontend:task_import' list.id %}">Import a task</a><br>
    
    <a href="{% url 'frontend:index' %}"> Return to the dashboard</a>
    
    
    <script src="{% static 'frontend/js/todolist.detail.js' %}">
    </script>
{% endblock %}

frontend/templates/frontend/todolist_form_create.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    
    {{ form }}
    <button id="submit">Submit</button>

    <script src="{% static 'frontend/js/todolist.list.js' %}"></script>

{% endblock %}

frontend/templates/frontend/wrong_method.html
<h3>This request method is not supported</h3>
<a href="{% url 'frontend:index' %}">Return to dashboard</a>